Fixes JsonProperty with no PropertyName value and adds tests
aliencube/AzureFunctions.Extensions pull request #103
Opened 2020-08-04 04:39 UTC by kylednoland

This PR fixes Issue #101 

In `PropertyInfoExtensions.cs` when the custom attribute does not have the PropertyName field populated, it currently returns `null` causing a thrown error further in the stack. This PR adds a fallback value to the `element.Name` property if the `PropertyName` is not populated. This adds support for attributes such as `[JsonProperty(Required.Default)]` and `[JsonProperty]`. I added two test cases to prove the functionality and all existing tests continue to pass.

2020-08-04 06:27 UTC, justinyoo commented
@kylednoland Thanks for the PR. I left a few comments for you to have a look.

2020-08-04 12:37 UTC, kylednoland commented
No problem @justinyoo! I'm not actually seeing any comments...am I missing them somewhere?

2020-08-06 10:43 UTC, justinyoo requested changes
@kylednoland Would you please have a look on my comment here?

2020-08-06 10:43 UTC, justinyoo commented on src/Aliencube.AzureFunctions.Extensions.OpenApi.Core/Extensions/PropertyInfoExtensions.cs
> +                var name = element.GetCustomAttribute<JsonPropertyAttribute>().PropertyName ?? element.Name;
Can we wrap the `element.Name` with `namingStrategy.GetPropertyName(...)`?

example:
https://github.com/aliencube/AzureFunctions.Extensions/blob/c53adaff65b33bacf7780272e3e36aaf87c2cf6f/src/Aliencube.AzureFunctions.Extensions.OpenApi.Core/Extensions/PropertyInfoExtensions.cs#L46

2020-08-06 10:43 UTC, justinyoo commented on test/Aliencube.AzureFunctions.Extensions.OpenApi.Core.Tests/Extensions/PropertyInfoExtensionsTests.cs
> +            var namingStrategy = new DefaultNamingStrategy();
We also need to consider `CamelCaseNamingStrategy`

2020-08-06 10:43 UTC, justinyoo commented on test/Aliencube.AzureFunctions.Extensions.OpenApi.Core.Tests/Extensions/PropertyInfoExtensionsTests.cs
> +            var namingStrategy = new DefaultNamingStrategy();
We also need to consider `CamelCaseNamingStrategy`

2020-08-06 10:44 UTC, justinyoo commented
I haven't submitted the comment... so it's been pending for a couple of days. My bad!

2020-08-07 23:59 UTC, kylednoland commented on src/Aliencube.AzureFunctions.Extensions.OpenApi.Core/Extensions/PropertyInfoExtensions.cs
> +                var name = element.GetCustomAttribute<JsonPropertyAttribute>().PropertyName ?? element.Name;
Thanks! I totally overlooked this, and it's now updated.

2020-08-08 00:00 UTC, kylednoland commented on test/Aliencube.AzureFunctions.Extensions.OpenApi.Core.Tests/Extensions/PropertyInfoExtensionsTests.cs
> +            var namingStrategy = new DefaultNamingStrategy();
Added a few tests for CamelCaseNamingStrategy

2020-08-08 00:00 UTC, kylednoland commented on test/Aliencube.AzureFunctions.Extensions.OpenApi.Core.Tests/Extensions/PropertyInfoExtensionsTests.cs
> +            var namingStrategy = new DefaultNamingStrategy();
Added a few tests for CamelCaseNamingStrategy

2020-08-08 00:00 UTC, kylednoland commented
No worries! I just pushed some updates that should resolve all comments. Please let me know if there is anything further!

2020-08-08 02:56 UTC, justinyoo commented
LGTM Thanks!

2020-08-08 02:56 UTC, merged